name: CI

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: "Run the workflow with tmate.io debugging enabled"
        required: true
        type: boolean
        default: false
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, reopened, labeled, synchronize ]

jobs:

  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        package:
          - image-hello
    steps:
      - uses: actions/checkout@v3
      - name: Setup Nix
        uses: ./.github/actions/setup-nix
      - name: Setup tmate debug session
        uses: mxschmitt/action-tmate@v3
        if: ${{ inputs.debug_enabled }}
      # - name: Build package
      #   run: nix build .#${{ matrix.package }}
